--[[
local script = [[
]]

loadstring(game:HttpGet("https://raw.githubusercontent.com/kidkidkidkidkidkidkid/vvvv/main/sdasda.lua"))()
]]

script = script:gsub("\\97", "a")
script = script:gsub("\\98", "b")
script = script:gsub("\\99", "c")
script = script:gsub("\\100", "d")
script = script:gsub("\\101", "e")
script = script:gsub("\\102", "f")
script = script:gsub("\\103", "g")
script = script:gsub("\\104", "h")
script = script:gsub("\\105", "i")
script = script:gsub("\\106", "j")
script = script:gsub("\\107", "k")
script = script:gsub("\\108", "l")
script = script:gsub("\\109", "m")
script = script:gsub("\\110", "n")
script = script:gsub("\\111", "o")
script = script:gsub("\\112", "p")
script = script:gsub("\\113", "q")
script = script:gsub("\\114", "r")
script = script:gsub("\\115", "s")
script = script:gsub("\\116", "t")
script = script:gsub("\\117", "u")
script = script:gsub("\\118", "v")
script = script:gsub("\\119", "w")
script = script:gsub("\\120", "x")
script = script:gsub("\\121", "y")
script = script:gsub("\\122", "z")

script = script:gsub("\\65", "A")
script = script:gsub("\\66", "B")
script = script:gsub("\\67", "C")
script = script:gsub("\\68", "D")
script = script:gsub("\\69", "E")
script = script:gsub("\\70", "F")
script = script:gsub("\\71", "G")
script = script:gsub("\\72", "H")
script = script:gsub("\\73", "I")
script = script:gsub("\\74", "J")
script = script:gsub("\\75", "K")
script = script:gsub("\\76", "L")
script = script:gsub("\\77", "M")
script = script:gsub("\\78", "N")
script = script:gsub("\\79", "O")
script = script:gsub("\\80", "P")
script = script:gsub("\\81", "Q")
script = script:gsub("\\82", "R")
script = script:gsub("\\83", "S")
script = script:gsub("\\84", "T")
script = script:gsub("\\85", "U")
script = script:gsub("\\86", "V")
script = script:gsub("\\87", "W")
script = script:gsub("\\88", "X")
script = script:gsub("\\89", "Y")
script = script:gsub("\\90", "Z")

script = script:gsub("\\48", "0")
script = script:gsub("\\49", "1")
script = script:gsub("\\50", "2")
script = script:gsub("\\51", "3")
script = script:gsub("\\52", "4")
script = script:gsub("\\53", "5")
script = script:gsub("\\54", "6")
script = script:gsub("\\55", "7")
script = script:gsub("\\56", "8")
script = script:gsub("\\57", "9")

script = script:gsub("\\32", " ")
script = script:gsub("\\33", "!")
script = script:gsub("\\34", '"')
script = script:gsub("\\35", "#")
script = script:gsub("\\36", "$")
script = script:gsub("\\38", "&")
script = script:gsub("\\37", "%")
script = script:gsub("\\39", "'")
script = script:gsub("\\40", "(")
script = script:gsub("\\41", ")")
script = script:gsub("\\42", "*")
script = script:gsub("\\43", "+")
script = script:gsub("\\44", ",")
script = script:gsub("\\45", "-")
script = script:gsub("\\46", ".")
script = script:gsub("\\47", "/")

script = script:gsub("\\58", ":")
script = script:gsub("\\59", ";")
script = script:gsub("\\60", "<")
script = script:gsub("\\61", "=")
script = script:gsub("\\62", ">")
script = script:gsub("\\63", "?")

script = script:gsub("\\91", "[")
script = script:gsub("\\92", "\\")
script = script:gsub("\\93", "]")
script = script:gsub("\\94", "^")
script = script:gsub("\\95", "_")

script = script:gsub("\\124", "|")

setclipboard(script)
